print("\n--/--/--/--/--/--/--/--/--/--/--/--/--/--/--/--/--/--/--/--/--/--/-")
print("Environment created.")
print("-------------------------------------------------------------------")
print("ENVIRONMENT CONSTANTS")
print("global_time:")
print("Target coordinates:")
print("Defense coordinates:")
print("Attack coordinates:")
print("-------------------------------------------------------------------")
print("****************")
print("ATTACK MISSILE")
print("****************")
